### ISSUE TITLE
Application view should utilise decorator to prohibit applicants and members

### ISSUE THREAD

**Issue by kieranw-8** [michaelmulianto/SEG-Team-Chickaree#18]
e.g. when a user attempts to apply to a club when there is already an open application or if they are already a member

**Comment by lclarkg18** [comment]
There aren't really errors to raise apart from empty (which doesn't raise a message, just a flag that hovers over the field), see how the login behaves for comparison

**Comment by lclarkg18** [comment]
Okay so I realised by coincidence that there are cases: when an application has already been made and when a user is already a member

**Comment by lclarkg18** [comment]
I have implemented messages for both cases but if (i) buttons aren't clickable when applied/member (as will be shortly, troll U05) and (ii) we implement a decorator that doesn't allow access to the page if applied/member then there wouldn't be a need for it

**Comment by lclarkg18** [comment]
I'll leave this open for that reason

**Comment by lclarkg18** [comment]
I think messages can be kept even if we are using decorators.

**Comment by lclarkg18** [comment]
Also I found out how to stack decorators:

@login_required(
        @applied_to_club(
            @member_of_club
        )
    )

**Comment by lclarkg18** [comment]
Decorators are implemented. Checking for owner is not easy because a user can be owner of several clubs. Meaning you need to pass in a club, member, applicant, ban, etc depending on which variable it is using. I know how to do this in Java by overwriting methods with same name but different variables but it doesn't seem easy in python. Maybe taking it in with kwargs and then have a switch/ifs to check what type it is and act accordingly.
